### PR TITLE
Add support for username during registration

### LINKED ISSUE #118: Add support for username during registration.
Reference : [link](https://github.com/Ignitus/Ignitus-client/issues/454)

### PR DESCRIPTION
**Pull request by ashutosh97**
Closes #118

## Description
- Changed models of user and profiles to add a field for username
- Modified the code for user registration

## Motivation and Context
Refer [link](https://github.com/Ignitus/Ignitus-client/issues/454)

## How Has This Been Tested?
Checked the requests using postman

## Screenshots (if appropriate):
Screenshot from 2020-03-03 20-07-44

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@ashutosh97 can you please resolve the merge conflicts 👍

**Comment by ashutosh97** [comment]
@divyanshu-rawat Hi. I resolved the conversations. I can't figure out why the labeler is giving an issue. Can you help?

**Comment by divyanshu-rawat** [comment]
> @ashutosh97 can you please resolve the merge conflicts 👍

Leave Labeler we can merge it even it fails, but please resolve `merge-conflicts` 👍

**Comment by ashutosh97** [comment]
@divyanshu-rawat Please review.

**Pull request closed without merging**
